apiVersion: v1
kind: Service
metadata:
  name: ispn-perf-test
spec:
  selector:
    name: ispn-perf-test
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    name: ispn-perf-test
    namespace: default
  spec:
    replicas: 2
    selector:
    template:
      metadata:
        labels:
          name: ispn-perf-test
      spec:
        subdomain: ispn-perf-test
        containers:
        - args:
          - /opt/jgroups/IspnPerfTest/bin/kube-dns.sh
          - -nohup
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: belaban/ispn_perf_test
          name: ispn-perf-test
          resources: {}
          terminationMessagePath: /dev/termination-log
kind: List
metadata: {}

